### ISSUE TITLE
can't compile example in arduino IDE

### ISSUE THREAD

**Issue by fjgaston** [garygru/yummyDSP#2]
hi,
I just tried to compile the Yummy basic example using Arduinon IDE and I have this error
```
src/AudioDriver.cpp: In member function 'int AudioDriver::setup(int, int, int, int, int, int, int, i2s_port_t)':
src/AudioDriver.cpp:84:3: sorry, unimplemented: non-trivial designated initializers not supported
```
in the example the setup command as only 7 items :
`i2sCodec.setup(fs, channelCount, I2S_BCK_PIN, I2S_LRCLK_PIN, I2S_DOUT_PIN, I2S_DIN_PIN, CODEC_ENABLE_PIN);`

but the AudioDriver.cpp expect 8, I don't know how to add the 8th :
`int AudioDriver::setup(int fs, int channelCount, int bitClkPin, int lrClkPin, int dataOutPin, int dataInPin, int enablePin, i2s_port_t i2s_port)`

**Comment by garygru** [comment]
yeah, the parameters have default values so they are optional (see the header). The last one is I2S_NUM_0. IMO no need to add that but give it a try.  
I think the problem is more of that it expects integers and the given values are defines and const int:

```
// I2S
const int fs = 48000;
const int channelCount = 2;

// Audio Amp Pins
#define I2S_BCK_PIN 26
#define I2S_LRCLK_PIN 27
#define I2S_DOUT_PIN 14
#define I2S_DIN_PIN 13
#define CODEC_ENABLE_PIN 33
```
try to remove the const label and/or change the #define to int:

```
// I2S 
int fs = 48000;
int channelCount = 2;

// Audio Amp Pins
int I2S_BCK_PIN 26
...
```

**Comment by fjgaston** [comment]
just did this :
```
// I2S
int fs = 48000;
int channelCount = 2;

// Audio Amp Pins
int I2S_BCK_PIN = 5;
int I2S_LRCLK_PIN = 16;
int I2S_DOUT_PIN = 25;
int I2S_DIN_PIN = 18;
int CODEC_ENABLE_PIN = 4;   
```
and I still have the same error

```
/Users/user/Documents/Arduino/libraries/yummyDSP-master/src/AudioDriver.cpp: In member function 'int AudioDriver::setup(int, int, int, int, int, int, int, i2s_port_t)':
/Users/user/Documents/Arduino/libraries/yummyDSP-master/src/AudioDriver.cpp:84:3: sorry, unimplemented: non-trivial designated initializers not supported
   };
   ^
/Users/user/Documents/Arduino/libraries/yummyDSP-master/src/AudioDriver copy.cpp: In member function 'int AudioDriver::setup(int, int, int, int, int, int, int, i2s_port_t)':
/Users/user/Documents/Arduino/libraries/yummyDSP-master/src/AudioDriver copy.cpp:84:3: sorry, unimplemented: non-trivial designated initializers not supported
   };
   ^
exit status 1
Error compiling for board ESP32 Dev Module.
```

**Comment by garygru** [comment]
Strange. what about
`i2sCodec.setup(fs, channelCount, I2S_BCK_PIN, I2S_LRCLK_PIN, I2S_DOUT_PIN, I2S_DIN_PIN, CODEC_ENABLE_PIN, I2S_NUM_0);` ?

are you on windows? never tried to compile it there.

**Comment by fjgaston** [comment]
I'm on mac, I tried this and had the same error.
Did you compile on linux ? I have another computer with linux, I can try on this one

**Comment by garygru** [comment]
Ok, the problem is not the function call but the next struct inside. Espressif added a member in between so it is no more compatible:

```
static const i2s_config_t i2s_config = {
				.mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_RX | I2S_MODE_TX),
				.sample_rate = fs,
				.bits_per_sample = I2S_BITS_PER_SAMPLE_24BIT,
				.channel_format = I2S_CHANNEL_FMT_RIGHT_LEFT, // switch to left only?
				.communication_format = (i2s_comm_format_t)(I2S_COMM_FORMAT_I2S | I2S_COMM_FORMAT_I2S_MSB),
				.intr_alloc_flags = ESP_INTR_FLAG_LEVEL1, // high interrupt priority
				.dma_buf_count = 2,
				.dma_buf_len = AudioDriver::BufferSize,
				.use_apll = true,
                                .tx_desc_auto_clear = true, // <= add this one
				.fixed_mclk = mclk_rate
		};
```

**Comment by fjgaston** [comment]
Awesome, it now compiles.
I'm trying it now with a PCM1802 and a PCM5102 with a WROOM32 board, I'll tell you how it goes

**Comment by fjgaston** [comment]
Well it works, if I decrease the sampling frequency to 22050, if I go to 44100 or 48000 it seems like the esp32 board is not able to output the master clock signal. I even soldered the GPIO0 pin as close as possible to the pcm1801 clock input.
It may be because it's a cheap banggood ESP32 board

**Comment by garygru** [comment]
Great! You can lower the master clock. Depends on the adc / dac. It’s currently 384*fs.

**Comment by fjgaston** [comment]
I think I found were the problem come from. The GPIO0 is connected to the "boot" button on the ESP32 board and it is also connected to a ~1nF capcitor to gnd. I guess it explains why the higher the frequency is the lower the voltage of GPIO0 is :-/

**Comment by fjgaston** [comment]
That's it! I removed this tiny capacitor and now it works well at 48k
