### ISSUE TITLE
Not an issue just thought I would ask ask.

### ISSUE THREAD

**Issue by StuartIanNaylor** [garygru/yummyDSP#4]
I have been thinking about how to digitally do the same as this analogue application.
https://invensense.tdk.com/wp-content/uploads/2015/02/Microphone-Array-Beamforming.pdf

So stereo I2S stream split tracks and add delay & invert one then sum back as a mono stream.

If you ever fancy giving it a go please do as interested as using mems with some directionality would be a great plus to the omnidirectional nature.

**Comment by garygru** [comment]
Yes, got for it! It should be no big deal. You'll probably want the highest sample rate available or even better a fractional delay because sample delay is a bit coarse, otherwise. 
If you need help let me know. I'm going to add a minimal hardware abstraction soon. So these MEMS mics should work fine then.

**Comment by StuartIanNaylor** [comment]
Need loads of help :) I am learning C slowly and the ESP32 wrover and been playing with voice AI and can realise the advantage but playing catch-up with skills needed.

The noise rejection and directionality only helps with background noise but being able to point a mic at a source does help much over what a omnidirectional will provide.
I have been looking blankly at https://github.com/atomic14/ICS-43434-breakout-board

As in https://github.com/atomic14/ICS-43434-breakout-board/blob/main/sketch/I2SSampler.cpp

Its converted to 16bit here but guess its also where the Endfire beamforming could go.

```
void I2SSampler::processI2SData(uint8_t *i2sData, size_t bytes_read)
{
    int32_t *samples = (int32_t *)i2sData;
    for (int i = 0; i < bytes_read / 4; i++)
    {
        // you may need to vary the >> 11 to fit your volume - ideally we'd have some kind of AGC here
        addSample(samples[i] >> 11);
    }
}
```

I am going to try but hoping I can get more competent interested as I am not sure how much load this will eventually take.
From the above invensense app note we always have this trade off between sampling rate, mic distance and frequency effects.

I am pretty confident the ESP32 could make a great wifi beamforming mic, but also less confident but if it could also squeeze in the KWS of   https://www.youtube.com/watch?v=re-dSV_a0tM&t=345s

I have been thinking for a while that distributed microphone arrays if cheap and easy enough could be beneficial to some of the snake oil wrapped up in high tech beamformers that are costly but also much less effective than many try to present them as.

But yeah I would really like to see what sort of results you can produce if you play about with mic spacing and sampling rate.
The KWS is a bonus if it will squeeze to only broadcast mic until silence so you can hook up to an ASR/Intent processor that definately will be too much for the ESP.
So after KWS hit you broadcast a ASR sentence until detected silence and also send the KW hit value data so you can pick from a distributed array of KWS mics and select the best audio as its just the highest or only KW hit.

So fingers crossed I might triggered your curiosity :)
